spring.application.name=Project1

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/job_automation_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Email Configuration (JavaMailSender)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:a27792652@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:ibemdeitdybzwzhi}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Groq API Configuration for Phase 4
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY:ENTER_YOUR_GROQ_API_KEY_HERE}
