spring.application.name=Project1

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://bvwrfmoe6rel3kmf3vuq-mysql.services.clever-cloud.com:3306/bvwrfmoe6rel3kmf3vuq}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:uid4oicn8yalaec1}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:74RHyP6YzZMpj3dahHYV}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Connection Pool Limits (For Clever Cloud Free Tier)
spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:2}
spring.datasource.hikari.minimum-idle=${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:1}
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Email Configuration (Resend REST API)
resend.api.key=${RESEND_API_KEY:re_SWWjzhjr_9RUDp59Ea5DY7wdDWVNpUEsw}

# Groq API Configuration for Phase 4
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY:ENTER_YOUR_GROQ_API_KEY_HERE}
